<a href="https://colab.research.google.com/github/siri2511/Deep-Learning/blob/main/BackPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import graphviz
def sigmoid(x):
  return 1/(1+np.exp(-x))
def sigmoid_derivative(x):
  return x*(1-x)
import graphviz
import numpy as np
def draw_neural_network(weights_input_hidden, weights_hidden_output, biases_hidden, biases_output, title):
    dot = graphviz.Digraph()
    # Input layer
    dot.node('I1', 'Input 1')
    dot.node('I2', 'Input 2')
    # Hidden layer
    dot.node('H1', 'Hidden 1')
    dot.node('H2', 'Hidden 2')
    # Output layer
    dot.node('O1', 'Output')
    # Input to hidden connections
    dot.edge('I1', 'H1', label=f'{weights_input_hidden[0,0]:.2f}')
    dot.edge('I1', 'H2', label=f'{weights_input_hidden[0,1]:.2f}')
    dot.edge('I2', 'H1', label=f'{weights_input_hidden[1,0]:.2f}')
    dot.edge('I2', 'H2', label=f'{weights_input_hidden[1,1]:.2f}')
    # Hidden to output connections
    dot.edge('H1', 'O1', label=f'{weights_hidden_output[0,0]:.2f}')
    dot.edge('H2', 'O1', label=f'{weights_hidden_output[1,0]:.2f}')
    # Bias nodes (added to input and hidden layers)
    dot.node('Bias_H1', f'Bias H1: {biases_hidden[0,0]:.2f}', shape='ellipse', color='lightblue')
    dot.node('Bias_H2', f'Bias H2: {biases_hidden[0,1]:.2f}', shape='ellipse', color='lightblue')
    dot.node('Bias_O', f'Bias O: {biases_output[0,0]:.2f}', shape='ellipse', color='lightblue')
    # Bias edges
    dot.edge('Bias_H1', 'H1', style='dashed')
    dot.edge('Bias_H2', 'H2', style='dashed')
    dot.edge('Bias_O', 'O1', style='dashed')
    # Title
    dot.attr(label=title, fontsize='20')
    return dot
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])
np.random.seed(42)
input_size = 2
hidden_size = 2
output_size = 1
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_hidden = np.random.uniform(size=(1, hidden_size))
bias_output = np.random.uniform(size=(1, output_size))
print("Initial weights_input_hidden:")
print(weights_input_hidden)
print("Initial weights_hidden_output:")
print(weights_hidden_output)
before_training = draw_neural_network(weights_input_hidden, weights_hidden_output, bias_hidden, bias_output, 'Before Training')
before_training.render('before_training', format='png', view=True)
learning_rate = 0.5
epochs = 10000
for epoch in range(epochs):
  hidden_layer_input = np.dot(X,weights_input_hidden)+bias_hidden
  hidden_layer_output = sigmoid(hidden_layer_input)
  output_layer_input = np.dot(hidden_layer_output,weights_hidden_output)+bias_output
  predicted_output = sigmoid(output_layer_input)
  error = y-predicted_output
  d_predicted_output = error*sigmoid_derivative(predicted_output)
  error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
  d_hidden_layer = error_hidden_layer*sigmoid_derivative(hidden_layer_output)
  weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output)*learning_rate
  bias_output += np.sum(d_predicted_output,axis = 0,keepdims = True)*learning_rate
  weights_input_hidden += X.T.dot(d_hidden_layer)*learning_rate
  bias_hidden += np.sum(d_hidden_layer,axis = 0,keepdims = True)*learning_rate
  if epoch%1000 == 0:
    loss = np.mean(np.square(error))
    print(f'Epoch {epoch}, Loss: {loss}')
    print("Updated weights_input_hidden:")
    print(weights_input_hidden)
    print("Updated weights_hidden_output:")
    print(weights_hidden_output)
after_training = draw_neural_network(weights_input_hidden, weights_hidden_output,bias_hidden,bias_output,'After Training')
after_training.render('after_training',format = 'png',view = True)
print("Predicted Output: \n",predicted_output)
print("Actual Output: \n",y)


Initial weights_input_hidden:
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
Initial weights_hidden_output:
[[0.15601864]
 [0.15599452]]
Epoch 0, Loss: 0.287974821321425
Updated weights_input_hidden:
[[0.37366036 0.950455  ]
 [0.73098815 0.59855624]]
Updated weights_hidden_output:
[[0.10353032]
 [0.09020048]]
Epoch 1000, Loss: 0.053295211915457386
Updated weights_input_hidden:
[[2.15392192 4.67735538]
 [2.16941747 4.76463046]]
Updated weights_hidden_output:
[[-4.8011087 ]
 [ 5.00701792]]
Epoch 2000, Loss: 0.003353714253243706
Updated weights_input_hidden:
[[3.69913436 5.70015601]
 [3.70582    5.73187636]]
Updated weights_hidden_output:
[[-8.0272169 ]
 [ 7.42129347]]
Epoch 3000, Loss: 0.0015572766528967937
Updated weights_input_hidden:
[[4.01166656 5.94708687]
 [4.0172208  5.97161021]]
Updated weights_hidden_output:
[[-8.76633097]
 [ 8.10832829]]
Epoch 4000, Loss: 0.0009962986277053856
Updated weights_input_hidden:
[[4.18122529 6.08625883]
 [4.1861823  6.1074413 ]]
Updated weights_h